---
{{/* Make sure all variables are set properly */}}
{{- include "common.values.setup" . }}


{{/* Append the hardcoded settings */}}
{{- define "alarmserver.hardcodedValues" -}}
persistence:
  alarmserver-config:
    enabled: "true"
    mountPath: "/app/alarmserver.cfg"
    subPath: "alarmserver.cfg"
    type: "custom"
    volumeSpec:
      configMap:
        name: {{ printf "%v-config" (include "common.names.fullname" .) }}
{{- end -}}
{{- $_ := mergeOverwrite .Values (include "alarmserver.hardcodedValues" . | fromYaml) -}}

{{/* Render the templates */}}
{{ include "common.all" . }}
